// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }


import NavBar from "../_components/NavBar";
import SideBar from "../_components/SideBar";


export default function DashBoardLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  
  return (
   
    <div className="flex h-screen overflow-hidden">
        <SideBar/>
        <div className="w-full h-screen overflow-auto">
          <NavBar />
          {children}
        </div>
    </div>
    
  )
}