import { NextResponse } from "next/server";
import { InferenceClient } from "@huggingface/inference";
import { db } from '@/firebase/firebaseAdmin';
import { FieldValue,Filter } from "firebase-admin/firestore";
import nodemailer from "nodemailer";
import OpenAI from "openai";

export async function POST(req: Request) {
  const { prompt,siteId,userId,userName,email,checkIn,checkOut } = await req.json();
  const date = new Date().getTime()



  try {
  // 🔐 Optional domain check (recommended)
    const siteDoc = await db.collection("users").doc(siteId).get();
    
    if (!siteDoc.exists) {
      return NextResponse.json({ error: "You are not registered on the ai concierge platform" }, { status: 403 });
    }
    const usersData = siteDoc?.data()?.users.find((user:any)=>user.userId ===userId)
  
    // save user if unregistered
    if (!usersData) {
  
      const transporter = nodemailer.createTransport({
        service:"gmail",
        auth:{
          user:process.env.EMAIL_NAME,
          pass:process.env.EMAIL_PASSWORD
        }
      })
      
      await transporter.sendMail({
        from:'Ai Concierge',
        to:email, // widget owner email
        subject:`new message received from ${userName}`,
        text:`new message received: ${prompt}. from ${userName} with ID: ${userId}`
      }).catch((err:any)=>console.log('error alerting new message',err))
  
      await db.collection("users").doc(siteId).update({users:FieldValue.arrayUnion({userName:userName,userId:userId,isEscalated:false,mostRecent:prompt,sendTime:date})})
    }
   
    
    try {
      

      // add the prompt to db
      await db.collection("users").doc(siteId).collection("externalUsers").doc(userId+siteId).collection("messages").add({message: prompt,senderId: userId,customerName:userName,receiverId: siteId,createdAt:date,isAi:true})
      .then(async ()=>{
        await db.collection("users").doc(siteId).update({messageCount:FieldValue.increment(1)})
        .catch(err=>console.log('increment failure',err))
      })
       
      
      // ai processing
      const client = new OpenAI({apiKey:process.env.OPEN_AI_API});
   
     
      const response = await client.responses.create({
        model: "gpt-5-nano",
        input:`IMPORTANT INFORMATION(do not reiterate this in the response,this request is from an api call)  countrylocation=${siteDoc?.data().country} , city=${siteDoc?.data().city} check-in-time=${checkIn} check-out-time=${checkOut}  room-services=[massages,haircuts,free drinks] GIVE A DIRECT RESPONSE NO QUESTIONS`+ prompt 
        
      });
      
     // save message generated by ai

      await db.collection("users").doc(siteId).collection("externalUsers").doc(userId+siteId).collection("messages").add({message:response.output_text,senderId: siteId,customerName:'Concierge Ai',receiverId: userId,createdAt:date +1,isAi:true})
      .then(async ()=>{
        // if message is saved increment the count
        await db.collection("users").doc(siteId).update({messageCount:FieldValue.increment(1)})
        .catch(err=>console.log('increment failure',err))
      })

      return NextResponse.json({
        result: response.output_text
      });
    } catch (error) {
      console.log('ai error',error);
      
        return NextResponse.json({
          error: 'Error saving ai message'
        },{status:500});
    }



    
  } catch (error) {
    console.error(error);
    return NextResponse.json(
      { error: "AI request failed" },
      { status: 500 }
    );
  }
}
